FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py migrate
RUN python manage.py createsuperuser --noinput || true

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]